version: '3.1'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
        - "9090:9090"

  grafana:
    image: grafana/grafana
    user: root
    volumes:
      #datasorces & dashboard
      - ./grafana_config/main.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./grafana_config/main-dashboard.json:/var/lib/grafana/dashboards/main-dashboard.json
      - ./grafana_config/datasouce.yml:/etc/grafana/provisioning/datasources/datasouce.yml

      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    ports:
      - "3000:3000"
