version: '3.1'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./prometheus_data:/prometheus
    ports:
        - "9090:9090"
