management:
  metrics:
    enable:
      all: false
      products: true
      http:
        server:
          requests: false
      db: true
  endpoints:
    web:
      exposure:
        include: prometheus,health,metrics

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
