FROM grafana/grafana

ADD main.yml /etc/grafana/provisioning/dashboards/main.yml
ADD main-dashboard.json /var/lib/grafana/dashboards/main-dashboard.json
ADD datasouce.yml /etc/grafana/provisioning/datasources/datasouce.yml
