{
 "title": "Metric dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Products count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    { "expr": "product_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB methods MAX seconds",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_find_by_id_seconds_max", "legendFormat": "__auto" },
    {
     "expr": "db_get_count_of_all_products_seconds_max",
     "legendFormat": "__auto"
    },
    { "expr": "db_save_seconds_max", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "HTTP requests sec MAX",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http request count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}